application: gae-php-mail
version: 1
runtime: php
api_version: 1

handlers:

- url: /mail
  script: mail.php
  login: required

- url: /mail_sent
  script: mail_sent.php
  login: required

- url: /.*
  script: index.php

